//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsBulmaProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class favori
    {
        public int favoriId { get; set; }
        public int KullaniciID { get; set; }
        public int ilanId { get; set; }
    
        public virtual Ilan Ilan { get; set; }
        public virtual Kullanici Kullanici { get; set; }
    }
}
