//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsBulmaProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IsBulmaEntities : DbContext
    {
        public IsBulmaEntities()
            : base("name=IsBulmaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Basvuru> Basvuru { get; set; }
        public virtual DbSet<favori> favori { get; set; }
        public virtual DbSet<Ilan> Ilan { get; set; }
        public virtual DbSet<IlanPozisyonSeviye> IlanPozisyonSeviye { get; set; }
        public virtual DbSet<IsKategori> IsKategori { get; set; }
        public virtual DbSet<IsVerenKayit> IsVerenKayit { get; set; }
        public virtual DbSet<Kullanici> Kullanici { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Yetenek> Yetenek { get; set; }
        public virtual DbSet<v_IlanlarByIsVerenId> v_IlanlarByIsVerenId { get; set; }
        public virtual DbSet<v_KullaniciBasvurular> v_KullaniciBasvurular { get; set; }
    }
}
