//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsBulmaProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_IlanlarByIsVerenId
    {
        public int isVerenId { get; set; }
        public int ilanId { get; set; }
        public string ilanAdi { get; set; }
        public string isVerenSirketAdi { get; set; }
        public int isKategoriId { get; set; }
        public Nullable<int> PozisyonSeviyeId { get; set; }
        public Nullable<System.DateTime> IlanEklenmeTarihi { get; set; }
        public Nullable<int> ilanBasvuruSayisi { get; set; }
        public string ilanSehir { get; set; }
        public string ilanCalismaBicimi { get; set; }
        public string IlanTanitim { get; set; }
    }
}
