//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsBulmaProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_KullaniciBasvurular
    {
        public int KullaniciID { get; set; }
        public string KullaniciAdi { get; set; }
        public string kullaniciSoyadi { get; set; }
        public string Mail { get; set; }
        public string CVdosyaPath { get; set; }
        public int ilanId { get; set; }
    }
}
